name: txt_docx
description: A simple tool that could convert plain text files to docx files and vice versa

version: 1.0.0
repository: https://github.com/lindeer/txt-docx

environment:
  sdk: ^3.0.0

dependencies:
  xml: ^6.5.0
  archive: ^4.0.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
